# - name: Grand Old Test-Bed
#   hosts: all
#   become: true
#   gather_facts: false
# vars:
#   myuser: anna
# vars_files:
# - variables.yaml
# - sensitive.anva
# - alreadyexists.anva
# - loop_items.yaml
# - variables1.yaml
# tasks:
# - name: "Enforce SELinux"
#   ansible.posix.selinux:
#     policy: targeted
#     state: enforcing
# - name: Creating user {{ myuser }}
#   ansible.builtin.user:
#     name: "{{ myuser }}"
#     shell: /bin/bash
#     state: absent
#   register: variab
# - name: Printing variab
#   ansible.builtin.debug:
#     msg: Here is the contents of "{{ variab }}"
# - name: Getting facts
#   ansible.builtin.debug:
#     var: ansible_facts["all_ipv4_addresses"]  # {{ not needed cuz it runs in a jinja template already, so it'll lead to double interpolation
#     var: ansible_facts["memory_mb"]["swap"]["free"]
#     msg: >
#       IP of this host is {{ ansible_facts.default_ipv4.address }}
# - name: Demo set_fact
#   ansible.builtin.set_fact:
#     myfirstfact: saturday
#     mysecondfact: evening
# - name: Demo again.
#   ansible.builtin.debug:
#     msg: Recording this on {{  myfirstfact }} {{  mysecondfact }}
# - name: New task to demo set_fact
#   ansible.builtin.debug:
#     msg: it is still {{  myfirstfact }} {{  mysecondfact }}
# - name: Demo ansible_mounts in ansible_facts
#   ansible.builtin.debug:
#     msg: Value is {{ ansible_facts["mounts"][29]["block_size"] }}
# - name: Demo register
#   register: dateval
#   ansible.builtin.command:
#     cmd: date
# - name: Debug
#   ansible.builtin.debug:
#     # var: dateval.stdout
#     var: dateval["stdout"]
# - name: Demo vault for new file
#   ansible.builtin.debug:
#     msg: >
#       This is the contents of the new vault file: {{ password }}
# - name: Demo vault for existing file
#   ansible.builtin.debug:
#     msg: >
#       This is the contents of the new vault file: {{ password1 }}

# - name: Demo loop
#   ansible.builtin.debug:
#     msg: "{{ item }}"
#   loop:
#     - vsftpd
#     - httpd
#     - sshd

# - name: Looping over a variable
#   ansible.builtin.debug:
#     msg: The loop item is {{ item }}
#   loop: "{{ loopingstuff }}"

# - name: Demo hashed loop items
#   ansible.builtin.debug:
#     msg: User name is {{ item.uname }} and group is {{ item.ugroups }}
#   loop: "{{ myusers }}"

# - name: Demo handlers, force_handlers
#   hosts: rhel9clients
#   force_handlers: true
#   tasks:
#     - name: Copy file
#       ansible.builtin.copy:
#         src: /tmp/index.html
#         dest: /var/www/html/index.html
#         mode: "0644"
#       # notify:
#       #   - Restart Web
#     - name: Install httpd
#       ansible.builtin.dnf:
#         name: httpd
#         state: present
#     - name: Copy non-existing file
#       ansible.builtin.copy:
#         src: /tmp/doesnotexist12
#         dest: /var/www/html/doesnotexist.html
#         mode: "0644"
#       notify:
#         - Restart Web
#   handlers:
#     - name: Restart Web
#       ansible.builtin.debug:
#         msg: The handler has run

# - name: Demo flush_handlers
#   hosts: centos7clients
#   gather_facts: false
#   tasks:
#     - name: Copy uevent file
#       ansible.builtin.copy:
#         src: /tmp/uevent
#         dest: /tmp/
#         mode: "0644"
#       notify:
#         - Copy handler
#     - name: Flush handlers
#       ansible.builtin.meta: flush_handlers
#     - name: Copy another file
#       ansible.builtin.copy:
#         src: /tmp/index.html1
#         dest: /tmp/
#         mode: "0644"
#   handlers:
#     - name: Copy handler
#       ansible.builtin.debug:
#         msg: The handler has run

# - name: Demo when
#   gather_facts: true
#   hosts: all
#   vars:
#     vmfilter:
#       - client1-vm-rhel9
#       - server1-vm-rhel10
#   tasks:
#     - name: VM-specific installation
#       ansible.builtin.debug:
#         # msg: This_word_is_needed {{ ansible_facts.hostname }} is in {{ vmfilter }}
#         msg: available size is greater than 10 GB
#       loop: "{{ ansible_facts['mounts'] }}"
#       when:
#         # ansible_hostname in vmfilter and "14" in ansible_date_time["day"]
#         # - ansible_hostname in vmfilter
#         #  # - "13" in ansible_date_time["day"]
#         # - ansible_memfree_mb > 512
#         - item["size_available"] < 10485760000 and item["mount"] == "/"

# - name: Demo vars_prompt
#   hosts: localhost
#   gather_facts: false
#   vars_prompt:
#     name: user_name
#     prompt: which user are you looking for ?
#     private: false
#   tasks:
#     - name: Checking whether we found {{ user_name }}
#       ansible.builtin.command: cat /etc/passwd
#       register: passwd_contents
#     - name: Printing {{ user_name }}
#       ansible.builtin.debug:
#         var: passwd_contents
#     - name: Printing the passwd file
#       ansible.builtin.debug:
#         msg: echo passwd contains user {{ user_name }}
#       when: passwd_contents["stdout"].find(user_name) != -1

# - name: Demo block with rescue and always keywords
#   hosts: remote
#   tasks:
#     - name: Will be "success"
#       when: ansible_distribution == "RedHat"
#       block:
#         - name: Creating a file
#           ansible.builtin.command:
#             cmd: touch /var/www/html/index.html
#           changed_when: false
#         - name: Restart rsyslog
#           ansible.builtin.service:
#             name: rsyslog
#             state: started
#       rescue:
#         - name: Date
#           ansible.builtin.shell: date
#         - name: Create a file
#           ansible.builtin.shell:
#             cmd: touch /tmp/rescue_completed
#       always:
#         - name: Log a message
#           ansible.builtin.shell: logger hello

# - name: Demo ignore_errors
#   hosts: rhel9clients
#   gather_facts: false
#   ignore_errors: true
#   tasks:
#     - name: Copy file
#       ansible.builtin.copy:
#         src: /tmp/uevent1
#         dest: /tmp
#         mode: "0600"
#     - name: Copy another file
#       ansible.builtin.copy:
#         src: /tmp/uevent
#         dest: /tmp
#         mode: "0600"

# - name: Demo ignore_errors and force_handlers combo
#   hosts: rhel9clients
#   gather_facts: false
#   ignore_errors: true
#   force_handlers: false
#   tasks:
#     - name: Copy file
#       ansible.builtin.shell:
#         cmd: "lsss /tmp"
#         # src: /tmp/uevent12
#         # dest: /tmp/
#         # mode: "0600"
#     - name: Another
#       ansible.builtin.shell:
#         cmd: "echosss"
#       # - name: Debug
#       #   ansible.builtin.debug:
#       #     msg: Yellow
#       notify: Demogorgon
#   handlers:
#     - name: Demogorgon  # Runs if debug is commented, because it becomes the handler of the last task, because the shell task is not idempotent, and only if the shell task doesn't fail
#       ansible.builtin.debug:
#         msg: The handler has run

# - name: Illustrate failed_when
#   hosts: centos7clients
#   gather_facts: false
#   tasks:
#     - name: Failing command
#       ansible.builtin.command:
#         cmd: "echo hello world"
#       ignore_errors: true # Can be at task level too.
#       register: retval
#       failed_when: "'world' in retval.stdout"
#     - name: Next # Task will be run even if previous task failed
#       ansible.builtin.debug:
#         msg: The task has run despite error in previous task
#     # - name: Should fail
#     #   ansible.builtin.command:
#     #     cmd: "echooooo"

# - name: Exemplify fail module
#   hosts: centos7clients
#   gather_facts: false
#   ignore_errors: true
#   tasks:
#     - name: Running echo
#       ansible.builtin.command: "echo Hello, world!"
#       register: retval
#     - name: The module of the task
#       ansible.builtin.fail:
#         msg: fail module fail
#       when: "'world' in retval.stdout"
#     - name: Running debug
#       ansible.builtin.debug:
#         msg: This is the msg in debug

# - name: Exemplify stat and assert
#   hosts: rhel9clients
#   gather_facts: false
#   tasks:
#     - name: Running stat
#       ansible.builtin.stat:
#         path: /etc/hosts
#       register: statreg
#     - name: Assert that /etc/hosts is a directory
#       ansible.builtin.assert:
#         that: statreg.stat.isdir

# - name: Another example
#   hosts: rhel9clients
#   gather_facts: false
#   vars_prompt:
#     - name: file_size
#       prompt: Wot's the file size in MiB ?
#       private: false
#   tasks:
#     - name: Is the file size within the window ?
#       ansible.builtin.assert:
#         that:
#           - (file_size | int) >= 1
#           - (file_size | int) <= 10
#         fail_msg: file size IS NOT between 1 and 10, aborting
#         success_msg: file size IS between 1 and 10, continuing
#     - name: Create file
#       ansible.builtin.command: dd if=/dev/random of=random_file bs=1 count={{ file_size }}

# - name: Non-idempotent command module
#   hosts: rhel9clients
#   gather_facts: false
#   become: true
#   tasks:
#     - name: The command
#       ansible.builtin.command: useradd joan
#       register: addeduser
#     - name: Run debug
#       ansible.builtin.debug:
#         msg: I do not get printed in the second-time execution cuz I'm not idempotent

- name: Idempotent command module
  hosts: rhel9clients
  gather_facts: true
  become: true
  ignore_errors: true
  tasks:
    - name: The command
      ansible.builtin.command: useradd joan
      register: addeduser
    - name: Exit code 9 is OK
      ansible.builtin.assert:
        that:
          - addeduser.rc == 9
        success_msg: User already exists and that's OK cuz we're idempotent now
    - name: Running debug
      ansible.builtin.debug:
        msg: Debug has run

# - name: "Ping"
#   ansible.builtin.ping: null
# - name: "Print"
#   ansible.builtin.debug:
#   msg: "Hello, world!"
# - name: Install EPEL repo.
#   yum: name=epel-release state=present

# - name: Import Remi GPG key.
#   rpm_key:
#     key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
#     state: present

# - name: Install Remi repo.
#   yum:
#     name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
#     state: present

#     - name: Check list of running Node.js apps.
#       command: /usr/local/bin/forever list
#       register: forever_list
#       changed_when: false
#
#     - name: Start example Node.js app.
#       command: "/usr/local/bin/forever start {{ node_apps_location }}/app/app.js"
#       when: "forever_list.stdout.find(node_apps_location + '/app/app.js') == -1"

# - name: Ensure firewalld is stopped (since this is for testing).
#   service: name=firewalld state=stopped
# - name: Install Node.js and npm.
#   yum: name=npm state=present enablerepo=epel
# - name: Install Forever (to run our Node.js app).
#   npm: name=forever global=yes state=present
# - name: Ensure Node.js app folder exists.
#   file: "path={{ node_apps_location }} state=directory"
# - name: Copy example Node.js app to server.
#   copy: "src=app dest={{ node_apps_location }}"
# - name: Install app dependencies defined in package.json.
#   npm: path={{ node_apps_location }}/app

# - name: Install Apache.
#   yum:
#     name:
#       - httpd
#       - httpd-devel
#     state: present
# - name: Copy configuration files.
#   copy:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     owner: root
#     group: root
#     mode: 644
#   with_items:
#     - src: httpd.conf
#       dest: /etc/httpd/conf/httpd.conf
#     - src: httpd-vhosts.conf
#       dest: /etc/httpd/conf/httpd-vhosts.conf
# - name: Make sure Apache is started now and at boot.
#   service:
#     name: httpd
#     state: started
#     enabled: true

# - import_playbook: sync_time.yaml
# - import_playbook: "/home/punit/etc/ansible_test_bed/{{ import_from_extra_var }}"
# - name: "First Playbook"
#   hosts: all
#   environment:
#     TERM: xterm
#   vars:
#     url: "http://example.com/~user/blog/title/foo-bar-baz"
#     var_hosts: "{{ lookup('file', '/etc/hosts') }}"
#     motd_content: "{{ lookup('file', '/etc/motd') }}"
#     import_from_vars_keyword: /home/punit/etc/ansible_test_bed/imported_from_keyword.yaml
#   tasks:
#     - name: "Allow Access From 10.0.0.1"
#       become: true
#       ansible.builtin.iptables:
#         chain: "INPUT"
#         jump: "ACCEPT"
#         source: "10.0.0.1"
#         state: "absent"
#     - name: "Ensure Line In '.bashrc' Using 'lineinfile'"
#       ansible.builtin.lineinfile:
#         path: ".bashrc"
#         line: "export PS1='\n\\[\e[00;30m\\]#\\[\e[01;32m\\]$pLINENO\\[\e[00;30m\\]|\\[\e[01;34m\\]$?\\[\e[00;30m\\]|\\[\e[01;32m\\]`date +%F`\\[\e[00;30m\\]T\\[\e[01;34m\\]`date +%T`\\[\e[00;30m\\]|\\[\e[01;36m\\]\\u\\[\e[00;30m\\]@\\[\e[01;35m\\]\\h\\[\e[00;30m\\]:\\[\e[01;33m\\]\\w\\[\e[0m\\]\n\\[\e[01;31m\\]\\$\\[\e[0m\\] '"
#         state: "present"
#     - name: "Ensure Line In '.bashrc' Using 'copy'."
#       ansible.builtin.copy:
#         content: "export PS1='\\n\\[\\e[00;30m\\]#\\[\\e[01;32m\\]$LINENO\\[\\e[00;30m\\]|\\[\\e[01;34m\\]$?\\[\\e[00;30m\\]|\\[\\e[01;32m\\]`date +%F`\\[\\e[00;30m\\]T\\[\\e[01;34m\\]`date +%T`\\[\\e[00;30m\\]|\\[\\e[01;36m\\]\\u\\[\\e[00;30m\\]@\\[\\e[01;35m\\]\\h\\[\\e[00;30m\\]:\\[\\e[01;33m\\]\\w\\[\\e[0m\\]\\n\\[\\e[01;31m\\]\\$\\[\\e[0m\\] '\n"
#         dest: ".bashrc"
#
# # [
# #     {
# #         name: "My First Playbook",
# #         hosts: "all",
# #         tasks:
# #             [
# #                 {name: "Ping", ansible.builtin.ping: null},
# #                 {name: "Print", ansible.builtin.debug: {msg: "Hello, world!"}},
# #             ],
# #     },
# #     {
# #         name: "iptables",
# #         hosts: "all",
# #         tasks:
# #             [
# #                 {
# #                     name: "Allow Access From 10.0.0.1",
# #                     become: true,
# #                     ansible.builtin.iptables:
# #                         {
# #                             chain: "INPUT",
# #                             jump: "ACCEPT",
# #                             source: "10.0.0.1",
# #                             state: "absent",
# #                         },
# #                 },
# #             ],
# #     },
# #     {
# #         name: "Ensure Line Is In File",
# #         hosts: "all",
# #         tasks:
# #             [
# #                 {
# #                     name: "Line In '.bashrc' Using 'lineinfile'",
# #                     ansible.builtin.lineinfile:
# #                         {
# #                             path: ".bashrc",
# #                             line: "export PS1='\n\\[\u001b[00;30m\\]#\\[\u001b[01;32m\\]$LINENO\\[\u001b[00;30m\\]|\\[\u001b[01;34m\\]$?\\[\u001b[00;30m\\]|\\[\u001b[01;32m\\]`date +%F`\\[\u001b[00;30m\\]T\\[\u001b[01;34m\\]`date +%T`\\[\u001b[00;30m\\]|\\[\u001b[01;36m\\]\\u\\[\u001b[00;30m\\]@\\[\u001b[01;35m\\]\\h\\[\u001b[00;30m\\]:\\[\u001b[01;33m\\]\\w\\[\u001b[0m\\]\n\\[\u001b[01;31m\\]\\$\\[\u001b[0m\\] '",
# #                             state: "present",
# #                         },
# #                 },
# #                 {
# #                     name: "Line In '.bashrc' Using 'copy'",
# #                     ansible.builtin.copy:
# #                         {
# #                             content: "export PS1='\\n\\[\\e[00;30m\\]#\\[\\e[01;32m\\]$LINENO\\[\\e[00;30m\\]|\\[\\e[01;34m\\]$?\\[\\e[00;30m\\]|\\[\\e[01;32m\\]`date +%F`\\[\\e[00;30m\\]T\\[\\e[01;34m\\]`date +%T`\\[\\e[00;30m\\]|\\[\\e[01;36m\\]\\u\\[\\e[00;30m\\]@\\[\\e[01;35m\\]\\h\\[\\e[00;30m\\]:\\[\\e[01;33m\\]\\w\\[\\e[0m\\]\\n\\[\\e[01;31m\\]\\$\\[\\e[0m\\] '\n",
# #                             dest: ".bashrc",
# #                         },
# #                 },
# #             ],
# #     },
# # ]
#
# # - name: "Jinja2 Test Bed"
#       # - name: "Write to hostname"
#       #   ansible.builtin.template:
#       #       src: "templates/host_name.j2"
#       #       dest: "tmp/hostname"
#       # - name: "Write Template To A Text File"
#       #   ansible.builtin.template:
#       #       src: "templates/jinja2_test_bed.j2"
#       #       dest: "tmp/jinja2.txt"
#       # - name: "touch Files With An Optional Mode"
#       #   ansible.builtin.file:
#       #       path: "{{ item.fileName }}"
#       #       state: touch
#       #       mode: "{{ item.mode | default(omit) }}"
#       #   loop:
#       #       - fileName: tmp/foo
#       #       - fileName: tmp/bar
#       #         mode: "0444"
#       #       - fileName: tmp/baz
#       # - name: "Test Test1"
#       #   ansible.builtin.debug:
#       #       msg: "Matched pattern 1"
#       #   when: url is match("http://example.com/~user/blog/.*/foo-bar-baz")
#       # - name: "Test Test2"
#       #   ansible.builtin.debug:
#       #       msg: "Matched pattern 2"
#       #   when: url is search("user/.*/title/.*")
#       # - name: "Test Test3"
#       #   ansible.builtin.debug:
#       #       msg: "Matched pattern 3"
#       #   when: url is search("users")
#       # - name: "Test Test4"
#       #   ansible.builtin.debug:
#       #       msg: "matched pattern 4"
#       #   when: url is regex("example\.com/\w+/foo")
#       # - name: "Test Tests"
#       #   block:
#       #       - name: "Test Test1"
#       #         ansible.builtin.debug:
#       #             msg: "Matched pattern 1"
#       #         when: url is match("http://example.com/~user/blog/.*/foo-bar-baz")
#       #       - name: "Test Test2"
#       #         ansible.builtin.debug:
#       #             msg: "Matched pattern 2"
#       #         when: url is search("user/.*/title/.*")
#       #       - name: "Test Test3"
#       #         ansible.builtin.debug:
#       #             msg: "Matched pattern 3"
#       #         when: url is search("users")
#       #       - name: "Test Test4"
#       #         ansible.builtin.debug:
#       #             msg: "matched pattern 4"
#       #         when: url is regex("example\.com/\w+/foo")
#       #       - name: "Test Test5"
#       #         ansible.builtin.debug:
#       #             msg: "matched pattern 4"
#       #         when: url is not regex("example\.com/\w+/foo")
#       # - name: "Test lookup"
#       #  # become: true
#       #   block:
#       #       - name: "/etc/hosts"
#       #         ansible.builtin.debug:
#       #             msg: "Value of 'var_hosts' is {{ var_hosts }}"
#             # - name: "/etc/motd"
#             #   ansible.builtin.debug:
#             #       msg: "Value of 'motd_content' is {{ motd_content }}"  # ?
#       # - name: "lookup and q"
#       #   block:
#       #       - name: "lookup"
#       #         ansible.builtin.debug:
#       #             msg: "{format yaml{  item }}"
#       #         loop: "{{ lookup('ns.col.lookup_items', wantlist = True) }}"  # ?
#       #       - name: "q"
#       #         ansible.builtin.debug:
#       #             msg: "{{ item }}"
#       #         loop: "{{ q('ns.col.lookup_items') }}"  # ?
#       # - name: "Get Date And Time"  # ?
#       #   ansible.builtin.shell: date > date.out ; cat date.out
#       #  # changed_when: false
# - import_playbook: "{{ import_from_vars_keyword }}"
